# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jayakrushnan/code_base/mybase/Zync_vivado_project/Zync_vivado_project.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0.xci
# IP: The module: 'zynq7000_preset_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jayakrushnan/code_base/mybase/Zync_vivado_project/Zync_vivado_project.gen/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jayakrushnan/code_base/mybase/Zync_vivado_project/Zync_vivado_project.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0.xci
# IP: The module: 'zynq7000_preset_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jayakrushnan/code_base/mybase/Zync_vivado_project/Zync_vivado_project.gen/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
