# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq7000_preset/zynq7000_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset || ORIG_REF_NAME==zynq7000_preset} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_processing_system7_0_0/zynq7000_preset_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_processing_system7_0_0 || ORIG_REF_NAME==zynq7000_preset_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_gpio_0_0/zynq7000_preset_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_gpio_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_xbar_0/zynq7000_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_xbar_0 || ORIG_REF_NAME==zynq7000_preset_xbar_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_1/zynq7000_preset_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_1 || ORIG_REF_NAME==zynq7000_preset_auto_pc_1} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_0 || ORIG_REF_NAME==zynq7000_preset_auto_pc_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_ps7_0_axi_periph_0/zynq7000_preset_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq7000_preset_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_rst_ps7_0_50M_0/zynq7000_preset_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq7000_preset_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_bram_ctrl_0_0/zynq7000_preset_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_bram_ctrl_0_bram_0/zynq7000_preset_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==zynq7000_preset_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: /home/jayakrushnan/code_base/mybase/Zync_vivado_project/Zync_vivado_project.gen/sources_1/bd/zynq7000_preset/zynq7000_preset_ooc.xdc
